/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo;

import DAO.GenericDAOImplHibernate;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class AltaEMPLEADO extends javax.swing.JFrame {
      Empleado e= new Empleado();
        Tecnico t =new Tecnico();
        Desarrollador d =new Desarrollador();
        
        GenericDAOImplHibernate<Empleado> pe = new GenericDAOImplHibernate<>();
    /**
     * Creates new form AltaEMPLEADO
     */
    public AltaEMPLEADO() {
        initComponents();
        lenguaje.setEnabled(false);
        experiencia.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombreEmpleado = new javax.swing.JTextField();
        dniEmpleado = new javax.swing.JTextField();
        direccionEmpleado = new javax.swing.JTextField();
        telefonoEmpleado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        experiencia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lenguaje = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        altaEmpleado = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tecnico = new javax.swing.JRadioButton();
        desarrollador = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("EMPLEADO");

        jLabel2.setText("NOMBRE");

        jLabel3.setText("DNI");

        jLabel4.setText("DIRECCION");

        jLabel5.setText("TELEFONO");

        nombreEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreEmpleadoKeyTyped(evt);
            }
        });

        dniEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dniEmpleadoKeyTyped(evt);
            }
        });

        direccionEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                direccionEmpleadoKeyTyped(evt);
            }
        });

        telefonoEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoEmpleadoKeyTyped(evt);
            }
        });

        jLabel6.setText("EXPERIENCIA");

        experiencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                experienciaKeyTyped(evt);
            }
        });

        jLabel7.setText("LENGUAJE");

        lenguaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lenguajeKeyTyped(evt);
            }
        });

        jButton1.setText("CANCELAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        altaEmpleado.setText("ACEPTAR");
        altaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaEmpleadoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoria"));

        buttonGroup1.add(tecnico);
        tecnico.setText("TECNICO");
        tecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecnicoActionPerformed(evt);
            }
        });

        buttonGroup1.add(desarrollador);
        desarrollador.setText("DESARROLLADOR");
        desarrollador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desarrolladorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tecnico)
                .addGap(118, 118, 118)
                .addComponent(desarrollador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tecnico)
                    .addComponent(desarrollador)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGap(44, 44, 44)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(telefonoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                .addComponent(direccionEmpleado)
                                .addComponent(dniEmpleado)
                                .addComponent(nombreEmpleado)))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(altaEmpleado))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(57, 57, 57)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(lenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(76, 76, 76)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dniEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(direccionEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(telefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(altaEmpleado))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void altaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaEmpleadoActionPerformed
        // TODO add your handling code here:
      
        if (evt.getSource()== altaEmpleado){
            cargarDatos();
              JOptionPane.showMessageDialog(null, "Dado de Alta");
        }  
    }//GEN-LAST:event_altaEmpleadoActionPerformed

    private void nombreEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreEmpleadoKeyTyped
          mayusculasIngresada(evt);
    }//GEN-LAST:event_nombreEmpleadoKeyTyped

    private void dniEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dniEmpleadoKeyTyped
        char c =  evt.getKeyChar();
        if(((c < '0') || (c> '9')) && (c != '\b' /*corresponde a BACK_SPACE*/)&&(c !='.')){
              evt.consume();
          }
    }//GEN-LAST:event_dniEmpleadoKeyTyped

    private void direccionEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionEmpleadoKeyTyped
        mayusculasIngresada(evt);
    }//GEN-LAST:event_direccionEmpleadoKeyTyped

    private void lenguajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lenguajeKeyTyped
        mayusculasIngresada(evt);
    }//GEN-LAST:event_lenguajeKeyTyped

    private void tecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecnicoActionPerformed
       if(tecnico.isSelected()){
         lenguaje.setEnabled(false);
         lenguaje.setText("");
         experiencia.setEnabled(true);
       }
    }//GEN-LAST:event_tecnicoActionPerformed

    private void desarrolladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desarrolladorActionPerformed
        if(desarrollador.isSelected()){
         experiencia.setEnabled(false);
         experiencia.setText("");
         lenguaje.setEnabled(true);
       }
    }//GEN-LAST:event_desarrolladorActionPerformed

    private void experienciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_experienciaKeyTyped
       char c =  evt.getKeyChar();
        if(((c < '0') || (c> '9')) && (c != '\b' /*corresponde a BACK_SPACE*/)){
              evt.consume();
          }
    }//GEN-LAST:event_experienciaKeyTyped

    private void telefonoEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoEmpleadoKeyTyped
       char c =  evt.getKeyChar();
        if(((c < '0') || (c> '9')) && (c != '\b' /*corresponde a BACK_SPACE*/)&&(c !='-')){
              evt.consume();
          }
    }//GEN-LAST:event_telefonoEmpleadoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaEMPLEADO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaEMPLEADO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaEMPLEADO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaEMPLEADO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaEMPLEADO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaEmpleado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton desarrollador;
    private javax.swing.JTextField direccionEmpleado;
    private javax.swing.JTextField dniEmpleado;
    private javax.swing.JTextField experiencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lenguaje;
    private javax.swing.JTextField nombreEmpleado;
    private javax.swing.JRadioButton tecnico;
    private javax.swing.JTextField telefonoEmpleado;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos() {
        String nombre= nombreEmpleado.getText().toUpperCase();
        String dni= dniEmpleado.getText().toUpperCase();
        String domicilio=direccionEmpleado.getText().toUpperCase();
        String telefono= telefonoEmpleado.getText().toUpperCase();
           if (tecnico.isSelected()){
               System.out.print("emndkfkd");
               int experienciaT= Integer.parseInt(experiencia.getText());
               t.setDni(dni);
               t.setNombre(nombre);
               t.setDireccion(domicilio);
               t.setTelefono(telefono);
               t.setAniosExp(experienciaT);
               pe.Guardar(t);
           }else{ 
               if (desarrollador.isSelected()){
               String lenjuajeD = lenguaje.getText().toUpperCase();   
               d.setDireccion(domicilio);
               d.setDni(dni);
               d.setNombre(nombre);
               d.setTelefono(telefono);
               d.setLenguajeExp(lenjuajeD);
                pe.Guardar(d);
           }else{
            e.setDireccion(domicilio);
            e.setDni(dni);
            e.setNombre(nombre);
            e.setTelefono(telefono);     
            pe.Guardar(e);  
            
            }
        }
    }

    private void mayusculasIngresada(java.awt.event.KeyEvent evt) {
       char c= evt.getKeyChar();
          if(Character.isLowerCase(c)){
              String cad=(""+c).toUpperCase();
              c=cad.charAt(0);
              evt.setKeyChar(c);
          }
    }
         
}
