/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo;

import DAO.GenericDAOImplHibernate;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author usuario
 */
public class bajaUsuario extends javax.swing.JFrame {
    /**
     * Creates new form bajaUsuario
     */
   //  String [] columnNames = {"NOMBRE ","DIRECCION "};
    DefaultTableModel modelo = new DefaultTableModel();
    GenericDAOImplHibernate<Persona> pe = new GenericDAOImplHibernate<>();
    ArrayList<Persona> personas = (ArrayList<Persona>) pe.Buscar();
      
    public bajaUsuario() {
        initComponents();
        cargarCombo(personasCombo);
        setLocationRelativeTo(null);
        AutoCompleteDecorator.decorate(this.personasCombo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personasCombo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonas = new javax.swing.JTable();
        botonEliminar = new javax.swing.JButton();
        cancelarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        personasCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                personasComboItemStateChanged(evt);
            }
        });

        tablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "NOMBRE", "DIRECCION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaPersonas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tablaPersonasFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPersonas);

        botonEliminar.setText("ELIMINAR");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        cancelarUsuario.setText("CANCELAR");
        cancelarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(personasCombo, 0, 255, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(cancelarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminar)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminar)
                    .addComponent(cancelarUsuario))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarUsuarioActionPerformed
        // TODO add your handling code here:
      if (evt.getSource()== this.cancelarUsuario) {}
       dispose();
    }//GEN-LAST:event_cancelarUsuarioActionPerformed

    private void personasComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_personasComboItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED){
            cargarGrilla();
        }
    }//GEN-LAST:event_personasComboItemStateChanged

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
        if (evt.getSource()== this.botonEliminar){
            eliminarPersona();
            limpiarPantalla();
           // cargarCombo1();
             cargarCombo1();
            JOptionPane.showMessageDialog(null, "Eliminado"); 
            
        }   
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void tablaPersonasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablaPersonasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaPersonasFocusGained
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bajaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bajaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bajaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bajaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new bajaUsuario().setVisible(true);
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton cancelarUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox personasCombo;
    private javax.swing.JTable tablaPersonas;
    // End of variables declaration//GEN-END:variables

    private void cargarGrilla() {
        ArrayList<Persona> personasDCombo = new ArrayList<Persona>();
        modelo=(DefaultTableModel) tablaPersonas.getModel();
        List<Persona> aux=pe.BuscarPersona(personasCombo.getSelectedItem().toString());
        for (Persona pr:aux){
            for (int j = 0; j < modelo.getRowCount(); j++) {
                modelo.setValueAt(pr.getNombre(), j, 0);
                modelo.setValueAt(pr.getDireccion(), j, 1);
            }
         }
         personasDCombo.removeAll(aux);
    }

    private void eliminarPersona() {
        modelo=(DefaultTableModel) tablaPersonas.getModel();
        for (int j = 0; j < modelo.getRowCount(); j++) {
            String aux= modelo.getValueAt(j, 0).toString();
            List<Persona> auxiliar=pe.BuscarPersona(aux);
            for (Persona pr:auxiliar){
                pe.Eliminar(pr.getId());
                tablaPersonas= new JTable();
             }
        }
    }

    private void limpiarPantalla() {
         for (int j = 0; j < modelo.getRowCount(); j++) {
            modelo.setValueAt(" ", j, 0);
            modelo.setValueAt(" ", j, 1); 
        }
     
    }
    public ArrayList<Persona> cargarCombo (JComboBox x){
       
        for (Persona e : personas) {
         x.addItem(e.getNombre());
        }
        return personas;
    }
   private void cargarCombo1 (){
        for (int i=0;i<personasCombo.getItemCount(); i++){
         personasCombo.removeItemAt(i);
        }
        ArrayList<Persona> personas1 = (ArrayList<Persona>) pe.Buscar();
        for (Persona e : personas1) {
        personasCombo.addItem(e.getNombre());
        }   
    }
}

