/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author usuario
 */
public class VentanaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConsulta
     */
    public VentanaConsulta() {
        initComponents();
        setLocationRelativeTo(null);		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Altausuario = new javax.swing.JButton();
        BajaUsuario = new javax.swing.JButton();
        ModificacionUsuario = new javax.swing.JButton();
        herenciaboton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Altausuario.setText("ALTA");
        Altausuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltausuarioActionPerformed(evt);
            }
        });

        BajaUsuario.setText("BAJA");
        BajaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajaUsuarioActionPerformed(evt);
            }
        });

        ModificacionUsuario.setText("MODIFICAR");
        ModificacionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificacionUsuarioActionPerformed(evt);
            }
        });

        herenciaboton.setText("HERENCIA");
        herenciaboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                herenciabotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(herenciaboton, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ModificacionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addComponent(BajaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addComponent(Altausuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Altausuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BajaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ModificacionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(herenciaboton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AltausuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltausuarioActionPerformed
        // TODO add your handling code here:
         altaUsuario aUsuario= new altaUsuario();
         aUsuario.setVisible(true);
    }//GEN-LAST:event_AltausuarioActionPerformed

    private void BajaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajaUsuarioActionPerformed
        // TODO add your handling code here:
        bajaUsuario bUsuario = new bajaUsuario();
        bUsuario.setVisible(true);
    }//GEN-LAST:event_BajaUsuarioActionPerformed

    private void ModificacionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificacionUsuarioActionPerformed
        // TODO add your handling code here:
        ModificarUsuario mUsuario= new ModificarUsuario();
        mUsuario.setVisible(true);
    }//GEN-LAST:event_ModificacionUsuarioActionPerformed

    private void herenciabotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_herenciabotonActionPerformed
        // TODO add your handling code here:
        AltaEMPLEADO aE= new AltaEMPLEADO();
        aE.setVisible(true);
    }//GEN-LAST:event_herenciabotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Altausuario;
    private javax.swing.JButton BajaUsuario;
    private javax.swing.JButton ModificacionUsuario;
    private javax.swing.JButton herenciaboton;
    // End of variables declaration//GEN-END:variables
}
