CREATE TABLE PERSONA (
	ID_PERSON SERIAL NOT NULL,
	NOMBRE VARCHAR(50), 
	DIRECCION VARCHAR(50), 
        PRIMARY KEY(ID_PERSON)

);

CREATE TABLE AUTO (
     ID_AUTO SERIAL NOT NULL, 
     MARCA VARCHAR(30), 	
     PATENTE VARCHAR(10), 
     ID_PERSON INT NOT NULL, 
     PRIMARY KEY(ID_AUTO)
  --   CONSTRAINT PK_PERSON FOREIGN KEY(ID_PERSON) REFERENCES PERSONA(ID_PERSON) ON DELETE CASCADE ///ON UPDATE(da error al eliminar la relacion agregando ON UPDATE)

);


ALTER TABLE AUTO ADD CONSTRAINT PK_PERSON FOREIGN KEY(ID_PERSON) REFERENCES PERSONA(ID_PERSON) ON DELETE CASCADE ON UPDATE CASCADE;